export const REVIEW_STATES = {
    LOADING: 'LOADING',
    READY: 'READY',
};

export const CANDIDATE_STATUSES = {
    INVITED: 'INVITED',
    INTERVIEW_IN_PROGRESS: 'INTERVIEW_IN_PROGRESS',
    INTERVIEW_COMPLETED: 'INTERVIEW_COMPLETED',
    PENDING_REVIEW: 'PENDING_REVIEW',
    UNDER_REVIEW: 'UNDER_REVIEW',
    SHORTLISTED: 'SHORTLISTED',
    NEXT_ROUND: 'NEXT_ROUND',
    HIRED: 'HIRED',
    REJECTED: 'REJECTED',
    WITHDRAWN: 'WITHDRAWN'
};
