export const REPLAY_STATES = {
    IDLE: 'IDLE',
    LOADING: 'LOADING',
    READY: 'READY',
    PLAYING: 'PLAYING',
    PAUSED: 'PAUSED',
    ENDED: 'ENDED',
    ERROR: 'ERROR'
};

export const TIMELINE_EVENT_TYPES = {
    QUESTION: 'QUESTION',
    ANSWER: 'ANSWER',
    VIOLATION: 'VIOLATION',
    MONITORING: 'MONITORING',
    SESSION_START: 'SESSION_START',
    SESSION_END: 'SESSION_END'
};
