export const VIOLATION_STATES = {
  ACTIVE: 'ACTIVE',
  RESOLVED: 'RESOLVED',
  IGNORED: 'IGNORED'
};

export const VIOLATION_SEVERITY = {
  WARNING: 'WARNING',
  CRITICAL: 'CRITICAL'
};

export const VIOLATION_SOURCES = {
  DEVICE: 'device',
  BROWSER: 'browser',
  FACE: 'face'
};

export const VIOLATION_TYPES = {
  NO_FACE: 'NO_FACE',
  MULTIPLE_FACES: 'MULTIPLE_FACES',
  PAGE_HIDDEN: 'PAGE_HIDDEN',
  WINDOW_BLURRED: 'WINDOW_BLURRED',
  OFFLINE: 'OFFLINE',
  FULLSCREEN_EXITED: 'FULLSCREEN_EXITED',
  CAMERA_DISCONNECTED: 'CAMERA_DISCONNECTED',
  MICROPHONE_DISCONNECTED: 'MICROPHONE_DISCONNECTED'
};
